config/routes.rb
Rails.application.routes.draw do
  get 'welcome/about', to: 'welcome#about', as: :about

  resources :movies do
  	collection do
  		get 'search'
  	end
    resources :reviews
  end

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  searchkick
  has_attached_file :poster, styles: { medium: "400x600#" }
  validates_attachment_content_type :poster, content_type: /\Aimage\/.*\Z/
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def search
    @movies = if params[:term].present?
      Movie.search(params[:term])
    else
      Movie.all
    end
  end
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = @movie.reviews.to_a
    @avg_rating = if @reviews.blank?
      0
    else
      @movie.reviews.average(:rating).round(2)
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :duration, :director, :rating, :description, :poster)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(controller_name, action_name)    
    "active" if current_page?(controller: controller_name, action: action_name)
  end
  
  def active_span(controller_name, action_name)
    "(current)" if current_page?(controller: controller_name, action: action_name)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse navbar-fixed-top">
  <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
  <ul class="nav navbar-nav">	

    <li class="nav-item <%= active_class('movies', 'new') %>">
	  <%= link_to new_movie_path, class: "nav-link" do %>
		New Movie
		<span class="sr-only"> <%= active_span('movies', 'new') %> </span>
	  <% end %>	  
    </li>	
	
    <li class="nav-item <%= active_class('welcome', 'about') %>">
	  <%= link_to about_path, class: 'nav-link' do %>
		About
		<span class="sr-only"> <%= active_span('welcome', 'about') %> </span>
	  <% end %>
    </li>
  </ul>
  
  <%= form_tag(search_movies_path, method: :get, class: "form-inline pull-xs-right", role: 'search') do %>
    <%= text_field_tag :term, params[:term], class: 'form-control' %>
	<%= submit_tag 'Search', name: nil, class: "btn btn-success-outline" %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnjanaMovieReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'layouts/header' %>
	<div id= 'wrapper' class="container">
	  <% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
	  <% end %>
	  
	  <%= yield %>
	</div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(movie, html: { multipart: true }) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group row">
    <%= f.label :title, class: 'col-sm-2 form-control-label' %>
	<div class="col-sm-6">
	  <%= f.text_field :title, class: 'form-control' %>
	</div>
  </div>
  <div class="form-group row">
    <%= f.label :duration, class: 'col-sm-2 form-control-label' %>
	<div class="col-sm-6">
      <%= f.text_field :duration, class: 'form-control' %>
	</div>
  </div>
  <div class="form-group row">
    <%= f.label :director, class: 'col-sm-2 form-control-label' %>
	<div class="col-sm-6">
      <%= f.text_field :director, class: 'form-control' %>
	</div>
  </div>
  <div class="form-group row">
    <%= f.label :rating, class: 'col-sm-2 form-control-label' %>
	<div class="col-sm-6">
	  <%= f.text_field :rating, class: 'form-control' %>
	</div>
  </div>
  
    Poster <br/>
	  <label class="file">
	    <%= f.label :poster, class: 'col-sm-2 form-control-label' %>
	    <%= f.file_field :poster %>
	    <span class="file-custom"></span>
	  </label>
  <div class="form-group row">
    <%= f.label :description, class: 'col-sm-2 form-control-label'  %>
	<div class="col-sm-6">
      <%= f.text_area :description, class: 'form-control' %>
	<div>
  </div>
  <br/>
  <div class="form-group row">
    <div class="col-sm-10">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
	  <%= link_to "Back", movies_path, class: "btn btn-secondary" %>
    </div>
  </div>
  
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="col-sm-6 col-md-5">
  <div class="thumbnail">
    <%= link_to (image_tag movie.poster.url(:medium), class: 'image'), movie %>
  </div>
  <hr/>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
<div class='jumbotron'>
	<h1> Your Favorite Movies Reviewed</h1>
	<p>
		Have you ever been to a movie and realized that it was so bad that you kick yourself for not reading the reviews? Kick yourself, no more. 
	</p>
	<p>
		<%= link_to 'Signup To Write a Review', root_path, class: 'btn btn-primary btn-lg' %>
	</p>
</div>

<div class="row">

<%= render @movies %>

</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

app/views/movies/search.html.erb
<div class="row">

<%= render @movies %>

</div>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.poster.url(:medium) %>
		<div class='star-rating' data-score=<%= @avg_rating %>></div>
		<em><%= "#{@reviews.size} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @movie.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @movie.description %></td>
              </tr>
              <tr>
                <td><strong>Movie length:</strong></td>
                <td><%= @movie.duration %></td>
              </tr>
              <tr>
                <td><strong>Director:</strong></td>
                <td><%= @movie.director %></td>
              </tr>
              <tr>
                <td><strong>Rating:</strong></td>
                <td><%= @movie.rating %></td>
              </tr>
            </tbody>
          </table>

        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @movie.title %></h1>

        <% if @reviews.blank? %>
          <h3>No reviews just yet. Would you like to add the first?</h3>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
		<%= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-primary" %>
      </div>
	  
    </div>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-10">
    <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-primary' %>
	<%= link_to "Back", movies_path, class: "btn btn-secondary" %>
  </div>
</div>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :rating, class: 'col-sm-2 form-control-label' %>
	<div class="col-sm-6" id='star-rating'></div>
  </div>

  <div class="form-group row">
    <%= f.label :comment, class: 'col-sm-2 form-control-label' %>
	<div class="col-sm-6">
      <%= f.text_area :comment, class: 'form-control' %>
	<div>
  </div>
  <br/>
  <div class="form-group row">
    <div class="col-sm-10">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
	  <%= link_to "Back", movies_path, class: "btn btn-secondary" %>
    </div>
  </div>

<% end %>

<script>
$('#star-rating').raty({
	path: '/assets',
	scoreName: 'review[rating]'
});
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Write a Review', new_movie_review_path(@movie) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/welcome/about.html.erb
<h1>About</h1>
<p>We are great. We do great things. You should do business with us. We dress nicely. You should also dress nicely if you want to work for us.</p>